apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: otel-collector-addon-manager
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: otel-collector
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: otel-collector
    spec:
      serviceAccount: otel-collector
      containers:
        - name: manager
          image: {{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect=true
