apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: otel-collector-addon-agent
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - coordination.k8s.io       
    resources:
      - leases
    verbs:
      - '*'