kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otel-collector-addon-agent
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otel-collector-addon-agent
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: {{ .Release.Namespace }}