apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: {{ .Release.Namespace }}
  labels:
    open-cluster-management.io/addon: otel-collector
    open-cluster-management.io/otel-component-name: otel-collector-config

data:
  relay: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s

    exporters:
      logging:
        loglevel: info

      jaeger:
        endpoint: {{ .Values.jaegerHubIp }}
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]