apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: {{ .Release.Namespace }}
  label:
    open-cluster-management.io/addon: otel-collector
spec:
  type: ClusterIP
  ports:
    - name: otlp
      port: 4317
      targetPort: otlp
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
  selector:
    open-cluster-management.io/addon: otel-collector