apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: {{ .Release.Namespace }}
  label:
    open-cluster-management.io/addon: otel-collector-addon
    otel.open-cluster-management.io/component-name: otel-collector-Service
spec:
type: ClusterIP
  ports:
    - name: otlp
      port: 4317
      targetPort: otlp
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
  selector:
    matchLabels:
      open-cluster-management.io/addon: otel-collector-addon
      otel.open-cluster-management.io/component-name: otel-collector
