apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: open-cluster-management-addon
  name: hub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      open-cluster-management.io/addon: otel-collector
      app: collector
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: otel-collector
        app: collector
    spec:
      serviceAccount: otel-collector
      containers:
        - name: otel-collector
          command:
            - /otelcol
            - --config=/conf/relay.yaml
          image: otel/opentelemetry-collector:0.56.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: otlp
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: collector-config
              mountPath: /conf
      volumes:
        - name: collector-config
          configMap:
            name: collector-config
            items:
              - key: relay
                path: relay.yaml
