apiVersion: v1
kind: Service
metadata:
  name: external-jaeger-service
  namespace: open-cluster-management-addon
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: collector
spec:
  ports:
  - name: port-1
    nodePort: 30584
    port: 14250
    protocol: TCP
    targetPort: 14250
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger
  type: NodePort