apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: open-cluster-management-addon
  labels:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: collector
spec:
  ports:
    - name: jaeger-collector-http
      port: 14250
      targetPort: 14250
      protocol: TCP
  selector:
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
  type: ClusterIP